/**
 * Kriterienkatalog B-COM - Betreiberpflichten und Compliance-Management,
 * Profilversion 1.0.0, Score-Art SS-MGMT.
 *
 * Bewertet die Steuerungs- und Organisationsfaehigkeit des Betreibers,
 * nicht den technischen Anlagenzustand (PRD 11.3, Anhang C).
 */

export const modules = [
  { key: "REG", label: "Betreiberpflichtenregister" },
  { key: "ROL", label: "Rollen und Kompetenz" },
  { key: "KAT", label: "Prueferfassung und Kataster" },
  { key: "MAS", label: "Massnahmen und Fristen" },
  { key: "NOT", label: "Notfallorganisation" },
  { key: "NAC", label: "Nachweise und Datenqualitaet" },
];

export const criteria = [
  {
    id: "B-COM-LRC-01",
    module: "REG",
    dimension: "LRC",
    weight: 5,
    mandatory: true,
    text: "Ein vollstaendiges, aktuelles Betreiberpflichtenregister mit Rechtsquelle, Frist und Verantwortlichem ist vorhanden.",
    guidance: "Vollstaendigkeit gegenueber Anlagenbestand und Bescheidlage pruefen.",
    sourceType: "gesetz",
    sourceRef: "Betreiberpflichten aus Rechts- und Bescheidgrundlagen",
    gateRule: { code: "KO-04", level: "stufe_c", fromSeverity: 3 },
  },
  {
    id: "B-COM-LRC-02",
    module: "REG",
    dimension: "LRC",
    weight: 4,
    mandatory: true,
    text: "Ein Rechtsmonitoring erfasst Aenderungen von Rechtsvorschriften und Bescheiden und loest Anpassungen aus.",
    guidance: "Quelle, Turnus, Verantwortlicher und Nachweis der letzten Auswertung.",
    sourceType: "fachbewertung",
    sourceRef: "Rechtsmonitoring-Prozess",
  },
  {
    id: "B-COM-TPF-01",
    module: "KAT",
    dimension: "TPF",
    weight: 4,
    mandatory: true,
    text: "Alle pruefpflichtigen technischen Anlagen sind im Kataster erfasst und einem Pruefregime zugeordnet.",
    guidance: "Abgleich Anlagenbestand, Kataster und tatsaechlich beauftragte Pruefungen.",
    sourceType: "fachbewertung",
    sourceRef: "Anlagen- und Pruefkataster",
  },
  {
    id: "B-COM-IPH-01",
    module: "MAS",
    dimension: "IPH",
    weight: 4,
    mandatory: true,
    text: "Personenkritische Risiken werden erkannt, priorisiert und mit kurzen Fristen gesteuert.",
    guidance: "Priorisierungsregel, Eskalationsstufen und Nachweis gelebter Anwendung.",
    sourceType: "fachbewertung",
    sourceRef: "Risikopriorisierungsregel",
  },
  {
    id: "B-COM-ORG-01",
    module: "ROL",
    dimension: "ORG",
    weight: 5,
    mandatory: true,
    text: "Zustaendigkeiten, Delegationen und Vertretungen fuer Betreiberpflichten sind schriftlich geregelt und angenommen.",
    guidance: "Bestellungen, Aufgabenumfang, Ressourcen und Annahmeerklaerung.",
    sourceType: "gesetz",
    sourceRef: "Delegations- und Bestellungsdokumente",
    gateRule: { code: "KO-04", level: "stufe_c", fromSeverity: 4 },
  },
  {
    id: "B-COM-ORG-02",
    module: "ROL",
    dimension: "ORG",
    weight: 3,
    mandatory: false,
    text: "Die fuer die Aufgaben erforderliche Qualifikation ist nachgewiesen und wird aktuell gehalten.",
    guidance: "Ausbildungen, Auffrischungen und Kompetenzmatrix.",
    sourceType: "fachbewertung",
    sourceRef: "Kompetenzmatrix",
  },
  {
    id: "B-COM-ORG-03",
    module: "NOT",
    dimension: "ORG",
    weight: 4,
    mandatory: true,
    text: "Die Notfall- und Alarmorganisation ist festgelegt, kommuniziert und regelmaessig geuebt.",
    guidance: "Alarmplan, Uebungsnachweise, Erreichbarkeiten.",
    sourceType: "gesetz",
    sourceRef: "Notfall- und Evakuierungspflichten",
  },
  {
    id: "B-COM-EVD-01",
    module: "NAC",
    dimension: "EVD",
    weight: 4,
    mandatory: true,
    text: "Pruefbefunde und Nachweise sind vollstaendig, auffindbar und einem Objekt eindeutig zugeordnet.",
    guidance: "Ablagestruktur, Zuordnung, Auffindbarkeit in Stichprobe.",
    sourceType: "fachbewertung",
    sourceRef: "Nachweisablage",
    gateRule: { code: "KO-06", level: "standard", fromSeverity: 4 },
  },
  {
    id: "B-COM-EVD-02",
    module: "NAC",
    dimension: "EVD",
    weight: 3,
    mandatory: false,
    text: "Die Datenqualitaet des Katasters wird periodisch geprueft und korrigiert.",
    guidance: "Stichprobenpruefung, Fehlerquote und Korrekturnachweis.",
    sourceType: "fachbewertung",
    sourceRef: "Datenqualitaetsprozess",
  },
  {
    id: "B-COM-MEA-01",
    module: "MAS",
    dimension: "MEA",
    weight: 5,
    mandatory: true,
    text: "Festgestellte Maengel werden mit Frist, Verantwortlichem, Status und Wirksamkeitsnachweis gefuehrt.",
    guidance: "Vollstaendiger Massnahmenlebenszyklus inklusive Abschlussnachweis.",
    sourceType: "fachbewertung",
    sourceRef: "Massnahmenmanagement",
    gateRule: { code: "KO-07", level: "standard", fromSeverity: 4 },
  },
  {
    id: "B-COM-MEA-02",
    module: "MAS",
    dimension: "MEA",
    weight: 4,
    mandatory: true,
    text: "Ueberfaellige und wiederholte Maengel werden automatisiert eskaliert und von der Fuehrung nachverfolgt.",
    guidance: "Eskalationsstufen, Berichtswesen und Managementreview.",
    sourceType: "fachbewertung",
    sourceRef: "Eskalationsregel",
  },
  {
    id: "B-COM-MEA-03",
    module: "KAT",
    dimension: "MEA",
    weight: 3,
    mandatory: false,
    text: "Prueffristen werden vorausschauend geplant; Fristueberschreitungen sind die Ausnahme und begruendet.",
    guidance: "Vorlauf, Terminplanung und Quote fristgerechter Pruefungen.",
    sourceType: "fachbewertung",
    sourceRef: "Pruefterminplanung",
  },
];

export default { modules, criteria };
