/**
 * Kriterienkatalog C-BAG - Betriebsanlagengenehmigung / Einreichprojekt,
 * Profilversion 1.0.0, Score-Art SS-READ (Reifegrad statt Istzustand).
 */

export const modules = [
  { key: "PRJ", label: "Projektgrundlagen" },
  { key: "REC", label: "Rechtsrahmen und Verfahren" },
  { key: "TEC", label: "Technische Schutzkonzepte" },
  { key: "PER", label: "Personenschutz und Evakuierung" },
  { key: "ORG", label: "Betriebsorganisation" },
  { key: "NAC", label: "Nachweise und Unterlagen" },
];

export const criteria = [
  {
    id: "C-BAG-LRC-01",
    module: "REC",
    dimension: "LRC",
    weight: 5,
    mandatory: true,
    text: "Der genehmigungspflichtige Umfang der Anlage ist vollstaendig und korrekt abgegrenzt.",
    guidance: "Anlagenteile, Betriebsweise, Emissionen und Nachbarschaftsbezug vollstaendig erfasst.",
    sourceType: "gesetz",
    sourceRef: "Gewerbeordnung - Genehmigungspflicht",
    gateRule: { code: "KO-04", level: "stufe_d", fromSeverity: 3 },
  },
  {
    id: "C-BAG-LRC-02",
    module: "REC",
    dimension: "LRC",
    weight: 4,
    mandatory: true,
    text: "Alle mitanzuwendenden Rechtsmaterien sind identifiziert und im Projekt beruecksichtigt.",
    guidance: "Arbeitnehmerschutz, Wasserrecht, Abfallrecht, Bau- und Elektrotechnikrecht abgleichen.",
    sourceType: "gesetz",
    sourceRef: "Materienregister des Projekts",
  },
  {
    id: "C-BAG-LRC-03",
    module: "REC",
    dimension: "LRC",
    weight: 4,
    mandatory: true,
    text: "Bestehende Bescheide, Auflagen und Aenderungsanzeigen sind erhoben und der Aenderungsbedarf ist abgeleitet.",
    guidance: "Bescheidhistorie und Konsensstand belegen.",
    sourceType: "bescheid",
    sourceRef: "Bescheidhistorie der Betriebsanlage",
  },
  {
    id: "C-BAG-TPF-01",
    module: "TEC",
    dimension: "TPF",
    weight: 5,
    mandatory: true,
    text: "Das Brandschutzkonzept ist schluessig, vollstaendig und mit den geplanten technischen Anlagen konsistent.",
    guidance: "Schutzziele, Abweichungen, Kompensationsmassnahmen und Anlagenumfang pruefen.",
    sourceType: "norm",
    sourceRef: "OIB-Richtlinien / TRVB-Regelwerk",
    gateRule: { code: "KO-03", level: "standard", fromSeverity: 4 },
  },
  {
    id: "C-BAG-TPF-02",
    module: "TEC",
    dimension: "TPF",
    weight: 4,
    mandatory: true,
    text: "Die geplanten sicherheitstechnischen Anlagen sind hinsichtlich Umfang, Schnittstellen und Ausfuehrbarkeit belastbar beschrieben.",
    guidance: "BMA, RWA, Sprinkler, Sicherheitsbeleuchtung und deren Wechselwirkung.",
    sourceType: "norm",
    sourceRef: "Anlagentechnische Regelwerke",
  },
  {
    id: "C-BAG-IPH-01",
    module: "PER",
    dimension: "IPH",
    weight: 5,
    mandatory: true,
    text: "Flucht- und Rettungswege sind fuer die geplante Personenbelegung ausreichend dimensioniert und nachgewiesen.",
    guidance: "Fluchtweglaengen, Breiten, Ausgaenge, Selbstrettungsfaehigkeit.",
    sourceType: "norm",
    sourceRef: "OIB-Richtlinie 2 / Arbeitsstaettenrecht",
    gateRule: { code: "KO-05", level: "standard", fromSeverity: 3 },
  },
  {
    id: "C-BAG-IPH-02",
    module: "PER",
    dimension: "IPH",
    weight: 4,
    mandatory: false,
    text: "Gefaehrdungen fuer Arbeitnehmer, Kunden und Nachbarn sind erhoben und mit Massnahmen hinterlegt.",
    guidance: "Laerm, Gefahrstoffe, Verkehr, Explosionsschutz und Nachbarschaftsschutz.",
    sourceType: "gesetz",
    sourceRef: "ASchG / Nachbarschaftsschutz",
  },
  {
    id: "C-BAG-ORG-01",
    module: "ORG",
    dimension: "ORG",
    weight: 3,
    mandatory: false,
    text: "Die kuenftige Betriebsorganisation inklusive Verantwortlichkeiten und Notfallorganisation ist beschrieben.",
    guidance: "Brandschutzbeauftragter, Unterweisung, Wartungsorganisation.",
    sourceType: "fachbewertung",
    sourceRef: "Betriebsbeschreibung",
  },
  {
    id: "C-BAG-EVD-01",
    module: "NAC",
    dimension: "EVD",
    weight: 5,
    mandatory: true,
    text: "Die Einreichunterlagen sind vollstaendig, aktuell, widerspruchsfrei und aufeinander abgestimmt.",
    guidance: "Plaene, Betriebsbeschreibung, Maschinenliste, Gutachten und Berechnungen gegeneinander pruefen.",
    sourceType: "gesetz",
    sourceRef: "Einreichunterlagen gemaess Verfahrensrecht",
    gateRule: { code: "KO-06", level: "standard", fromSeverity: 4 },
  },
  {
    id: "C-BAG-EVD-02",
    module: "PRJ",
    dimension: "EVD",
    weight: 3,
    mandatory: true,
    text: "Fachgutachten und Berechnungen sind von befugten Personen erstellt und nachvollziehbar.",
    guidance: "Befugnis, Datum, Annahmen und Rechenweg pruefen.",
    sourceType: "fachbewertung",
    sourceRef: "Gutachtenregister des Projekts",
  },
  {
    id: "C-BAG-MEA-01",
    module: "PRJ",
    dimension: "MEA",
    weight: 3,
    mandatory: false,
    text: "Offene Punkte aus Vorbesprechungen und Behoerdenrueckmeldungen sind nachverfolgt und abgearbeitet.",
    guidance: "Punkteliste mit Verantwortlichen, Fristen und Status.",
    sourceType: "fachbewertung",
    sourceRef: "Protokolle der Vorbesprechungen",
  },
];

export default { modules, criteria };
