/**
 * Kriterienkatalog T-BMA - Brandmeldeanlagen, Profilversion 1.0.0.
 *
 * Mindestmodule gemaess PRD 11.1.1: Ueberwachungsumfang; Melder und Gruppen;
 * Alarmierung; Uebertragung; Brandfallsteuerungen; Energieversorgung;
 * Feuerwehrschnittstellen; Dokumentation; Wartung.
 *
 * Die Quellenangaben verweisen auf das versionierte Quellenregister des
 * Profils (PRD 19). Konkrete Fundstellen werden dort gepflegt, nicht im Code.
 */

export const modules = [
  { key: "UMF", label: "Ueberwachungsumfang" },
  { key: "MEL", label: "Melder und Gruppen" },
  { key: "ALA", label: "Alarmierung" },
  { key: "UEB", label: "Uebertragung" },
  { key: "BFS", label: "Brandfallsteuerungen" },
  { key: "ENE", label: "Energieversorgung" },
  { key: "FWS", label: "Feuerwehrschnittstellen" },
  { key: "DOK", label: "Dokumentation" },
  { key: "WAR", label: "Wartung" },
];

export const criteria = [
  // ---------------------------------------------------------------- LRC
  {
    id: "T-BMA-LRC-01",
    module: "UMF",
    dimension: "LRC",
    weight: 5,
    mandatory: true,
    text: "Der ausgefuehrte Ueberwachungsumfang entspricht dem Bescheid beziehungsweise der behoerdlich vorgeschriebenen Schutzumfangskategorie.",
    guidance: "Abgleich Bescheid, Brandschutzkonzept und Ausfuehrung. Abweichungen des Schutzumfangs sind verbindliche Abweichungen.",
    sourceType: "bescheid",
    sourceRef: "Betriebsanlagenbescheid, Auflagen Brandmeldeanlage",
    gateRule: { code: "KO-04", level: "stufe_d", fromSeverity: 3 },
  },
  {
    id: "T-BMA-LRC-02",
    module: "DOK",
    dimension: "LRC",
    weight: 4,
    mandatory: true,
    text: "Die vorgeschriebene wiederkehrende Pruefung wurde fristgerecht und durch eine befugte Stelle durchgefuehrt.",
    guidance: "Prueffrist, Pruefbefugnis und Pruefumfang der letzten Pruefung nachweisen.",
    sourceType: "gesetz",
    sourceRef: "Gewerbeordnung / Landesrecht, wiederkehrende Pruefpflichten",
    gateRule: { code: "KO-04", level: "stufe_c", fromSeverity: 3 },
  },
  {
    id: "T-BMA-LRC-03",
    module: "UEB",
    dimension: "LRC",
    weight: 5,
    mandatory: true,
    text: "Die vorgeschriebene Alarmweiterleitung an die Feuerwehr beziehungsweise die beauflagte Stelle ist eingerichtet und zulaessig betrieben.",
    guidance: "Erforderlichkeit ergibt sich aus Bescheid oder Konzept. Fehlende geforderte Uebertragung ist nicht kompensierbar.",
    sourceType: "bescheid",
    sourceRef: "Bescheidauflage Alarmweiterleitung / Anschaltbedingungen",
    gateRule: { code: "KO-04", level: "stufe_d", fromSeverity: 3 },
  },
  {
    id: "T-BMA-LRC-04",
    module: "WAR",
    dimension: "LRC",
    weight: 3,
    mandatory: true,
    text: "Der Betreiber erfuellt die dokumentierten Betreiberpflichten fuer Betrieb, Instandhaltung und Stoerungsbehandlung der Anlage.",
    guidance: "Benannte verantwortliche Person, Vertretung, Stoerungsprozess und Betriebsbuchfuehrung.",
    sourceType: "gesetz",
    sourceRef: "Betreiberpflichten gemaess Rechts- und Bescheidgrundlage",
  },

  // ---------------------------------------------------------------- TPF
  {
    id: "T-BMA-TPF-01",
    module: "UMF",
    dimension: "TPF",
    weight: 4,
    mandatory: true,
    text: "Alle ueberwachungspflichtigen Bereiche sind tatsaechlich mit geeigneten Meldern erfasst; keine unzulaessigen Ueberwachungsluecken.",
    guidance: "Stichprobe je Brandabschnitt und Nutzungseinheit inklusive Zwischendecken und Doppelboeden.",
    sourceType: "norm",
    sourceRef: "TRVB S 123 - Brandmeldeanlagen",
    gateRule: { code: "KO-03", level: "standard", fromSeverity: 4 },
  },
  {
    id: "T-BMA-TPF-02",
    module: "MEL",
    dimension: "TPF",
    weight: 5,
    mandatory: true,
    text: "Die Stichprobenpruefung der automatischen Brandmelder ergibt eine ordnungsgemaesse Ansprechfunktion und korrekte Gruppenzuordnung.",
    guidance: "Mindeststichprobe gemaess Profilvorgabe; Ansprechverhalten und Anzeige an der Zentrale pruefen.",
    sourceType: "norm",
    sourceRef: "TRVB S 123 / OENORM EN 54",
    gateRule: { code: "KO-03", level: "standard", fromSeverity: 4 },
  },
  {
    id: "T-BMA-TPF-03",
    module: "MEL",
    dimension: "TPF",
    weight: 3,
    mandatory: false,
    text: "Handfeuermelder sind vorhanden, zugaenglich, gekennzeichnet und funktionsfaehig.",
    guidance: "Lage an Fluchtwegen, Freihaltung, Beschriftung und Funktionsausloesung.",
    sourceType: "norm",
    sourceRef: "TRVB S 123 - Handfeuermelder",
  },
  {
    id: "T-BMA-TPF-04",
    module: "MEL",
    dimension: "TPF",
    weight: 3,
    mandatory: false,
    text: "Die Brandmeldezentrale ist stoerungsfrei; keine dauerhaft abgeschalteten Meldergruppen ohne dokumentierte Ersatzmassnahme.",
    guidance: "Abschaltungen, Stoerungen und Revisionsschaltungen im Betriebsbuch nachweisen.",
    sourceType: "norm",
    sourceRef: "TRVB S 123 - Betriebszustaende",
  },
  {
    id: "T-BMA-TPF-05",
    module: "ALA",
    dimension: "TPF",
    weight: 5,
    mandatory: true,
    text: "Die akustische und optische Alarmierung ist im gesamten erforderlichen Alarmierungsbereich wirksam.",
    guidance: "Hoerbarkeit in allen Aufenthaltsbereichen, Alarmierungskonzept und Signalgeberverteilung pruefen.",
    sourceType: "norm",
    sourceRef: "TRVB S 123 - Alarmierungseinrichtungen",
    measurement: { unit: "dB(A)", min: 65, max: 120, label: "Schalldruckpegel im ungünstigsten Aufenthaltsbereich" },
    gateRule: { code: "KO-03", level: "exponiert", fromSeverity: 4 },
  },
  {
    id: "T-BMA-TPF-06",
    module: "UEB",
    dimension: "TPF",
    weight: 5,
    mandatory: true,
    text: "Die Uebertragungseinrichtung leitet Brand- und Stoerungsmeldungen nachweislich an die vorgesehene Stelle weiter.",
    guidance: "Aufschaltung, Rueckmeldung, Redundanz des Uebertragungsweges und Testalarm dokumentieren.",
    sourceType: "norm",
    sourceRef: "Anschaltbedingungen der Alarmempfangsstelle",
    gateRule: { code: "KO-03", level: "standard", fromSeverity: 4 },
  },
  {
    id: "T-BMA-TPF-07",
    module: "BFS",
    dimension: "TPF",
    weight: 5,
    mandatory: true,
    text: "Alle Brandfallsteuerungen loesen entsprechend der freigegebenen Steuermatrix aus.",
    guidance: "Steuerung von Brandschutzabschluessen, Aufzuegen, Lueftung, RWA, Sprachalarm und Abschaltungen einzeln pruefen.",
    sourceType: "norm",
    sourceRef: "Freigegebene Brandfallsteuermatrix des Objekts",
    gateRule: { code: "KO-03", level: "standard", fromSeverity: 3 },
  },
  {
    id: "T-BMA-TPF-08",
    module: "ENE",
    dimension: "TPF",
    weight: 4,
    mandatory: true,
    text: "Die Ersatzstromversorgung deckt die geforderte Ueberbrueckungsdauer und Alarmierungsreserve ab.",
    guidance: "Batteriekapazitaet, Alter, Ladeteil und Spannungswerte unter Last erfassen.",
    sourceType: "norm",
    sourceRef: "TRVB S 123 - Energieversorgung",
    measurement: { unit: "h", min: 4, max: 72, label: "nachgewiesene Ueberbrueckungsdauer" },
    gateRule: { code: "KO-03", level: "standard", fromSeverity: 4 },
  },
  {
    id: "T-BMA-TPF-09",
    module: "ENE",
    dimension: "TPF",
    weight: 3,
    mandatory: false,
    text: "Die Hauptenergieversorgung der Zentrale ist eigens abgesichert, gekennzeichnet und gegen unbeabsichtigtes Abschalten geschuetzt.",
    guidance: "Eigener Stromkreis, Kennzeichnung, Absicherung und Zugriffsschutz.",
    sourceType: "norm",
    sourceRef: "TRVB S 123 / Elektrotechnische Anforderungen",
  },
  {
    id: "T-BMA-TPF-10",
    module: "FWS",
    dimension: "TPF",
    weight: 4,
    mandatory: true,
    text: "Feuerwehrbedienfeld, Feuerwehranzeigetableau und Schluesselsafe sind funktionsfaehig und plausibel angezeigt.",
    guidance: "Anzeige, Bedienung, Beschriftung und Uebereinstimmung mit der Objektstruktur pruefen.",
    sourceType: "norm",
    sourceRef: "TRVB S 123 - Feuerwehrperipherie",
  },

  // ---------------------------------------------------------------- IPH
  {
    id: "T-BMA-IPH-01",
    module: "ALA",
    dimension: "IPH",
    weight: 5,
    mandatory: true,
    text: "Personen in allen Aufenthaltsbereichen werden im Alarmfall rechtzeitig und verstaendlich gewarnt.",
    guidance: "Beruecksichtigt Schlafbereiche, laute Bereiche, Barrierefreiheit und besonders schutzbeduerftige Personen.",
    sourceType: "fachbewertung",
    sourceRef: "Schutzziel Personenwarnung im Brandschutzkonzept",
    gateRule: { code: "KO-01", level: "standard", fromSeverity: 4 },
  },
  {
    id: "T-BMA-IPH-02",
    module: "BFS",
    dimension: "IPH",
    weight: 5,
    mandatory: true,
    text: "Flucht- und Rettungswege werden durch die Brandfallsteuerung nicht blockiert; Tueren und Aufzuege verhalten sich sicher.",
    guidance: "Fluchttuersteuerung, Aufzugsevakuierungsfahrt und Freischaltung im Alarmfall pruefen.",
    sourceType: "fachbewertung",
    sourceRef: "Flucht- und Rettungswegkonzept",
    gateRule: { code: "KO-05", level: "exponiert", fromSeverity: 4 },
  },
  {
    id: "T-BMA-IPH-03",
    module: "UMF",
    dimension: "IPH",
    weight: 4,
    mandatory: false,
    text: "Bereiche mit erhoehter Personengefaehrdung sind entsprechend ihrer Exposition ueberwacht und alarmiert.",
    guidance: "Beherbergung, Pflege, Versammlung, Kindergarten oder Bereiche mit eingeschraenkter Selbstrettung.",
    sourceType: "fachbewertung",
    sourceRef: "Nutzungsanalyse und Personenexposition",
  },
  {
    id: "T-BMA-IPH-04",
    module: "MEL",
    dimension: "IPH",
    weight: 3,
    mandatory: false,
    text: "Falschalarmrisiko ist so beherrscht, dass die Alarmakzeptanz der Nutzer erhalten bleibt.",
    guidance: "Haeufung von Taeuschungsalarmen mit Folge verzoegerter Reaktion oder Abschaltungen bewerten.",
    sourceType: "fachbewertung",
    sourceRef: "Betriebsbuchauswertung Taeuschungsalarme",
  },

  // ---------------------------------------------------------------- ORG
  {
    id: "T-BMA-ORG-01",
    module: "WAR",
    dimension: "ORG",
    weight: 4,
    mandatory: true,
    text: "Eine benannte, eingeschulte betriebliche Person ist fuer Bedienung, Stoerungsbehandlung und Alarmorganisation verantwortlich.",
    guidance: "Benennung, Vertretung, Erreichbarkeit und nachgewiesene Einschulung.",
    sourceType: "gesetz",
    sourceRef: "Betreiberorganisation gemaess Rechtsgrundlage",
  },
  {
    id: "T-BMA-ORG-02",
    module: "ALA",
    dimension: "ORG",
    weight: 3,
    mandatory: false,
    text: "Die Alarmorganisation inklusive Interventionszeiten, Erkundung und Evakuierungsentscheidung ist festgelegt und geuebt.",
    guidance: "Alarmplan, Erkundungsablauf und Nachweis der letzten Uebung.",
    sourceType: "fachbewertung",
    sourceRef: "Alarm- und Evakuierungsplan",
  },
  {
    id: "T-BMA-ORG-03",
    module: "DOK",
    dimension: "ORG",
    weight: 2,
    mandatory: false,
    text: "Das Betriebsbuch wird laufend, vollstaendig und nachvollziehbar gefuehrt.",
    guidance: "Eintraege zu Alarmen, Stoerungen, Abschaltungen, Pruefungen und Instandsetzungen.",
    sourceType: "norm",
    sourceRef: "TRVB S 123 - Betriebsbuch",
  },

  // ---------------------------------------------------------------- EVD
  {
    id: "T-BMA-EVD-01",
    module: "DOK",
    dimension: "EVD",
    weight: 4,
    mandatory: true,
    text: "Die Anlagendokumentation einschliesslich Melderplaene entspricht dem tatsaechlichen Ausfuehrungsstand.",
    guidance: "Aktualitaet der Plaene, Gruppenverzeichnis und Kennzeichnung gegenueber der Ausfuehrung pruefen.",
    sourceType: "norm",
    sourceRef: "TRVB S 123 - Anlagendokumentation",
    gateRule: { code: "KO-06", level: "standard", fromSeverity: 4 },
  },
  {
    id: "T-BMA-EVD-02",
    module: "BFS",
    dimension: "EVD",
    weight: 4,
    mandatory: true,
    text: "Eine freigegebene, aktuelle Brandfallsteuermatrix liegt vor und ist mit der Ausfuehrung abgeglichen.",
    guidance: "Ohne freigegebene Matrix ist die Wirksamkeit der Steuerungen nicht verifizierbar.",
    sourceType: "fachbewertung",
    sourceRef: "Brandfallsteuermatrix, Revisionsstand",
    gateRule: { code: "KO-06", level: "standard", fromSeverity: 4 },
  },
  {
    id: "T-BMA-EVD-03",
    module: "WAR",
    dimension: "EVD",
    weight: 3,
    mandatory: true,
    text: "Nachweise der vorgeschriebenen Wartungen und Funktionspruefungen der laufenden Periode liegen vollstaendig vor.",
    guidance: "Wartungsprotokolle, Pruefnachweise und Maengelvermerke der Fachfirma.",
    sourceType: "norm",
    sourceRef: "Wartungsvorgaben Hersteller und TRVB",
  },
  {
    id: "T-BMA-EVD-04",
    module: "UEB",
    dimension: "EVD",
    weight: 2,
    mandatory: false,
    text: "Der Nachweis der letzten Uebertragungs- und Aufschaltpruefung ist aktuell und plausibel.",
    guidance: "Protokoll der Alarmempfangsstelle oder des Errichters.",
    sourceType: "norm",
    sourceRef: "Anschaltbedingungen der Alarmempfangsstelle",
  },

  // ---------------------------------------------------------------- MEA
  {
    id: "T-BMA-MEA-01",
    module: "WAR",
    dimension: "MEA",
    weight: 4,
    mandatory: true,
    text: "Maengel aus Vorpruefungen und Wartungen wurden fristgerecht behoben und die Wirksamkeit nachgewiesen.",
    guidance: "Offene Punkte der Vorperiode, Fristen und Wirksamkeitsnachweise abgleichen.",
    sourceType: "fachbewertung",
    sourceRef: "Maengelliste Vorpruefung",
    gateRule: { code: "KO-07", level: "standard", fromSeverity: 4 },
  },
  {
    id: "T-BMA-MEA-02",
    module: "WAR",
    dimension: "MEA",
    weight: 4,
    mandatory: true,
    text: "Die vorgeschriebenen Wartungs- und Pruefintervalle werden eingehalten; keine ueberfaelligen Pflichtleistungen.",
    guidance: "Intervalltreue der letzten drei Perioden bewerten.",
    sourceType: "norm",
    sourceRef: "Wartungs- und Pruefintervalle des Profils",
  },
  {
    id: "T-BMA-MEA-03",
    module: "MEL",
    dimension: "MEA",
    weight: 3,
    mandatory: false,
    text: "Melder werden entsprechend Verschmutzung, Alterung und Herstellervorgabe getauscht oder gereinigt.",
    guidance: "Austauschzyklen, Verschmutzungswerte und Herstellervorgaben.",
    sourceType: "hersteller",
    sourceRef: "Herstellervorgaben Melderwartung",
  },
  {
    id: "T-BMA-MEA-04",
    module: "ENE",
    dimension: "MEA",
    weight: 3,
    mandatory: false,
    text: "Batterien werden innerhalb der vorgesehenen Nutzungsdauer getauscht und die Kapazitaet wird geprueft.",
    guidance: "Batteriedatum, Kapazitaetsmessung und Austauschplanung.",
    sourceType: "hersteller",
    sourceRef: "Herstellervorgaben Batteriewechsel",
    measurement: { unit: "V", min: 20, max: 30, label: "Batteriespannung unter Last (24-V-System)" },
  },
];

export default { modules, criteria };
